const ACTION_TYPES = {
  /*
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  */
  COUNTER_INCREMENT: Symbol(),
  COUNTER_DECREMENT: Symbol(),

  GET_USERS_REQUEST: Symbol(),
  GET_USERS_SUCCESS: Symbol(),
  GET_USERS_ERROR: Symbol(),
};

export default ACTION_TYPES;
