const ACTION_TYPES = {
  /*
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  */
  COUNTER_INCREMENT: Symbol(),
  COUNTER_DECREMENT: Symbol(),
};

export default ACTION_TYPES;
